#!/bin/bash
#set -x

case="[a-z]"
otherCase="[A-Z]"

if [ "$1" == "-r" ]; then
case="[A-Z]"
otherCase="[a-z]"
shift
fi

if [ "$#" -gt 0 ]; then
        for i in "$@"; do

        dir="$i"
        if [ -z $(echo $i | grep "/$") ]; then
                        dir="$i/"
        fi
        subdir="."
        (cd $i && ls -lAR) | grep "^[\.-]" | tr -s " " | cut -f9 -d" " |
        while read line; do
                        if [ -z $line ]; then
                                        :
                        elif [ -z $(echo $line | grep ":$") ]; then
                                        onlyStartCase=$( echo $line | grep $case)
                                        if [ -z $onlyStartCase ]; then
                                                        onlyOtherCase="$dir$subdir/$(echo $line | tr $otherCase $case)"
                                                        if [ -e "$onlyOtherCase" ]; then
                                                                        echo "File $onlyOtherCase already exists"
                                                        else
                                                                        mv "$dir$subdir/$line" "$onlyOtherCase"
                                                        fi
                                        fi
                        else
                                        subdir="$( echo $line | sed -E 's/^\.(.*)\:$/\1/g' )"
                        fi
        done

        done
else
        dir="./"
        subdir="."
        ls -lAR | grep "^[\.-]" | tr -s " " | cut -f9 -d" " |
        while read line; do
                        if [ -z $line ]; then
                                        :
                        elif [ -z $(echo $line | grep ":$") ]; then
                                        onlyStartCase=$( echo $line | grep $case)
                                        if [ -z $onlyStartCase ]; then
                                                        onlyOtherCase="$dir$subdir/$(echo $line | tr $otherCase $case)"
                                                        if [ -e "$onlyOtherCase" ]; then
                                                                        echo "File $onlyOtherCase already exists"
                                                        else
                                                                        mv "$dir$subdir/$line" "$onlyOtherCase"
                                                        fi
                                        fi
                        else
                                        subdir="$( echo $line | sed -E 's/^\.(.*)\:$/\1/g' )"
                        fi
        done
fi